### PR TITLE
Add documentation skeleton

### PR DESCRIPTION
**Pull request by willingc**
Addresses #101 

This PR provides the basic documentation structure in Sphinx for Read The Docs.

I've kept the source files as Markdown with the exception of the Table of Contents in rST.

Once this PR is merged, I'll begin breaking up the README.md into pages for the documentation.

screen shot 2016-03-06 at 4 36 04 pm

cc/ @parente

### CODE REVIEW

**Comment by rgbkrk** [comment]
Skeletor is welcome.

**Comment by willingc** [comment]
@rgbkrk I'm channeling @captainsafia today.


skeletor

@parente Travis will not win ;)

**Comment by parente** [comment]
That's exactly what I looked and felt like after fighting Travis last time.

How can I do anything but merge a PR with that in it?

**Comment by captainsafia** [comment]
*Safia emerges from a pile of schoolwork.*

giphy

*Safia re-enters pile of schoolwork.*

**Comment by willingc** [comment]
@parente Thanks!

My current favorite solution for terminating Travis (though not really practical): https://github.com/andig/volkszaehler.org/blob/master/.travis.yml#L119

**Comment by rgbkrk** [comment]
Quality GIFs all, :100:

**Pull request merged**
