### PR TITLE
Shutdown kernels on interrupt

### LINKED ISSUE #167: Disposing Running Kernels by Ctrl_C in RHEL
Hi 

Would be great if you could help me with the following problem.
I am running KernelGateway:

`jupyter kernelgateway --KernelGatewayApp.api='notebook-http' --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8090 --KernelGatewayApp.seed_uri=<.ipynb> --KernelGatewayApp.max_kernels=1` 

against Spark Cluster.

When I am trying to kill the process with CTRL+C it dies successfully (I can't see jupyter-kernelg via ps -a). However, my kernel (Apache Toree) clearly is up and running. I could see the kernel in Spark UI among Running Applications.

I am wondering if it might be related to the following code in Gateway::start

`   try:
           self.io_loop.start()
        except KeyboardInterrupt:
            self.log.info("Interrupted...")
`

where does not seem to be any attempt to call shutdown and hence dispose existing kernel_pool.
Am I missing anything obvious ?

Thank you
Andrey

### PR DESCRIPTION
**Pull request by parente**
Fixes #167

### CODE REVIEW

**Comment by jtyberg** [comment]
LGTM

**Comment by parente** [comment]
Tnx @jtyberg.

@gavrand if you can try the master branch in your environment, please let us know if it fixes your problem.

**Comment by gavrand** [comment]
Thank you, @parente and @jtyberg . I will try and come back  !

**Comment by gavrand** [comment]
@parente, I tried the fix today and it does fix the issue. I do not see the Kernel in SparkUI and Toree seems to be disappearing from process list `(ps -u <> )`.

Thank you !
Andrey

**Comment by parente** [comment]
@gavrand thanks for reporting and testing. :cake:

**Pull request merged**
