### PR TITLE
POST env extends default env

### PR DESCRIPTION
**Pull request by minrk**
rather than starting from scratch with an empty env, which resets PATH among other things.

cf failures in #238

### CODE REVIEW

**Comment by parente** [comment]
Thank you @minrk for tracking this down!

**Comment by parente** [comment]
Dawned on me in writing the release notes for 2.0 that this change introduces a problem whereby secrets in the kernel gateway process environment (e.g., `KG_TOKEN`) can now be seen by kernels spawned by the KG. Either we should document this behavior or whitelist which env vars we want kernels to inherit (e.g., `PATH`).

**Comment by rolweber** [comment]
I'd prefer the whitelist approach. I backported the change to 1.2.x and would rather not introduce a security-relevant change with a fixlevel.

**Comment by rolweber** [comment]
For the records, see PRs #248 (master) and #250 (1.2.x).
We're only passing the PATH variable instead of the full environment there.

**Pull request merged**
