### PR TITLE
Wrong super class in `super()`

### PR DESCRIPTION
**Pull request by Carreau**
I think, unless it's made on purpose ?

### CODE REVIEW

**Comment by parente** [comment]
You would think, except now all the tests are failing. So either the test is garbage or we should have doc'ed why we were skipping the parent class. (I don't think we were on purpose.)

**Comment by Carreau** [comment]
Hooray for tests.

**Comment by parente** [comment]
So, um, I'm getting a test failure on master totally unrelated to this PR, but somehow the last merge to master was green on travis. :joy:

I'll dig in.

**Comment by parente** [comment]
Fix text fixture problem in #139. Back to debugging the original problem ...

**Comment by parente** [comment]
#141 fixes the test failure problems.

**Pull request closed without merging**
