### PR TITLE
Issue 187: dev image build failure from missing dependency

### PR DESCRIPTION
**Pull request by nitind**
Adds the enchant package to the dev/test image
(c) Copyright IBM Corp. 2016

### CODE REVIEW

**Comment by nitind** [comment]
While it gets past the problem, I'm not sure this is the cleanest solution there could be.

**Comment by parente** [comment]
It's just the doc that fails building, right? It's strange that it's never had a problem before and we haven't changed the docker image.

**Comment by nitind** [comment]
Agreed. I suspect that dependencies in that environment, not being locked to specific versions, have changed to require this.

**Comment by parente** [comment]
I don't think pyenchant is even being used. Nor some of the other installs. 

Opening a new PR that only includes the libraries used in the dashboards project doc build.

**Pull request closed without merging**
