### PR TITLE
Update all swagger.json endpoints to support auth token header/query param

### PR DESCRIPTION
**Pull request by skbergam**

### CODE REVIEW

**Comment by rolweber** [comment]
I thought Swagger allows to define global security constraints, so that you don't have to add the same setting to each endpoint? See also issue #232, and this commit from the other pending PR: https://github.com/jupyter/kernel_gateway/pull/230/commits/fcf1316ee399a422fcad7185e5ca9cc77454d8ae

**Comment by skbergam** [comment]
@rolweber: maybe you're right, but I had to add these changes to enable the auth token on the other endpoints. could be that removing it from the one endpoint is all that was necessary for Swagger to infer it was meant to be global?

/cc @parente

**Comment by rolweber** [comment]
I merged the other PR that had swagger updates. Could you please check if that resolves your problem?
If not, please update this PR. I suggest to use a top-level `security` element. According to the [spec](http://swagger.io/specification/), it is...

"A declaration of which security schemes are applied for the API as a whole."

**Comment by parente** [comment]
I added the security requirements section in #244. I think we can close this PR. Thanks @skbergam.

**Pull request closed without merging**
