### PR TITLE
#229 update project overview in readme and docs

### PR DESCRIPTION
**Pull request by rolweber**
Here's my suggestion to address issue #229. The text is identical for README and docs.
You can check the formatted README in my branch: https://github.com/rolweber/kernel_gateway/tree/229_doc_updates

@BigLep - is this clear enough?
@parente - is it correct? :-)

### CODE REVIEW

**Comment by parente** [comment]
@rolweber Thanks for tackling this!

The only thought I had was also about mentioning how the KG is using the Jupyter Notebook code base under the covers, not reimplementing everything from scratch. On one hand, a statement like that acts as indicator of code maturity here (a question that is sometimes asked). On the other, it's  a technical detail that might be more confusing to first time visitors than helpful.

**Comment by rolweber** [comment]
@parente: Thanks for the suggestion. I found an unobtrusive way to mention it.

**Comment by parente** [comment]
Very nice. I like it. Let's timebox leaving this unmerged for others to comment, say til Monday. We can plan on making the 2.0 release next week after this goes in.

**Comment by BigLep** [comment]
Sorry for the delay.  The improvements look good to me.  My head has been out of this space, so don't have further comments for items in http://blog.jupyter.org/2016/03/09/jupyter-kernel-gateway/ and https://github.com/jupyter-incubator/proposals/blob/master/kernel_gateway/proposal.md that should make there way here.  Thanks!

**Comment by parente** [comment]
Thanks all. Let's merge and improve over time.

**Pull request merged**
