### PR TITLE
Docstrings for all tests

### PR DESCRIPTION
**Pull request by parente**
Fixed a few test name collisions too

Finishes the fixes for #115

### CODE REVIEW

**Comment by Carreau** [comment]
You seem to like some strong formatting consistencies. Do you want to activate something like https://landscape.io/ on this repo, which run some linter on the code base ? 

I'll review that in more details, but as it seem mostly cleanup,

+1

**Comment by parente** [comment]
Just following the recs from @willingc and @fperez about matching numpy syntax. I doubt as people contributes it'll be perfect forever. But, hey, starting on the right foot.

Not familiar with landscape.io. Are you using it on other jupyter projects?

**Comment by Carreau** [comment]
> Not familiar with landscape.io. Are you using it on other jupyter projects?

No, but as you said, starting on the right foot. 
Also on IPython & Notebook landscape choke a lot on traitlets, and find a lot of errors where there is none.

**Comment by willingc** [comment]
@Carreau landscape.io looks pretty interesting. If free for open source, it could be helpful.

**Comment by parente** [comment]
I don't mind if you want to try it. But if it gives a lot of false positives, we'll probably want to turn it back off.

**Comment by Carreau** [comment]
> I don't mind if you want to try it. But if it gives a lot of false positives, we'll probably want to turn it back off.

Ok, that would be easy, it does not see this repo, and the syncing with GitHub failed. So no landscape for now.

**Comment by Carreau** [comment]
Actually it works. 

There is a couple of false positive: https://landscape.io/github/jupyter/kernel_gateway/ we can likely tweak it.

**Comment by fperez** [comment]
Thanks so much @parente! 

But more importantly is the actual substance of having docstrings everywhere.  I really want this to become something we simply don't pass on, ever.  Projects like scikit-learn or sympy have set a great example of simply making good docs a necessary and inescapable part of the project's workflow, and we haven't.

Examples like this are a great step in the right direction.

ps - I'm not particularly picky about `'''` vs `"""`, though I prefer the latter and it's nice to see consistency :)

**Pull request merged**
