### PR TITLE
Update docs to be more informative on startup as per issue https://gi…

### PR DESCRIPTION
**Pull request by cottrell**
…thub.com/jupyter/kernel_gateway/issues/351

See https://github.com/jupyter/kernel_gateway/issues/351. 

I built the docs but didn't seem to create a diff so I'm assuming there is some doc build in the github pipelines.

### CODE REVIEW

**Review by kevin-bates — COMMENTED** [review]
Hi @cottrell - thank you for the pull request - this is great information.  My only comment is that I wonder if most of this belongs in the `Running` section: https://jupyter-kernel-gateway.readthedocs.io/en/latest/http-mode.html#running

Either that or I think we should make a point that these updates are relative only to the `notebook-http` mode and perhaps add an analogous entry for `jupyter-websocket` mode (which is the default).

Does that sound ok?

**Comment by cottrell** [comment]
Yes, what is the test for the websocket mode? I can add that in.

**Comment by kevin-bates** [comment]
Thank you David.

The startup output is a bit quieter...
```
jupyter kernelgateway --KernelGatewayApp.api=kernel_gateway.jupyter_websocket --port=10100
[KernelGatewayApp] Jupyter Kernel Gateway at http://127.0.0.1:10100
```
(and this option `--KernelGatewayApp.api=kernel_gateway.jupyter_websocket` is the default, but listed for completeness.)

You could hit the same swagger endpoint.  I  also like fetching the set of kernelspecs as a litmus test:
```
curl http://127.0.0.1:10100/api/kernelspecs
```
The output is a bunch of JSON that looks much better if piped through `jq` ( `... |  jq`).

**Comment by cottrell** [comment]
Updated again.

**Review by kevin-bates — APPROVED** [review]
Good stuff - thanks David!

**Pull request merged**
