### PR TITLE
HTTP mode example improvement

### LINKED ISSUE #201: Documentation request: GET requests paths with parameters for api_intro.ipynb
I can't grok this notebook (https://github.com/jupyter/kernel_gateway/blob/master/etc/api_examples/api_intro.ipynb) because request examples haven't been included.
I realise that this notebook could conform to some accepted standard, but I wouldn't know where to find the documentation.

I'd be grateful if someone could enlighten me with some example requests to endpoints such as:
* GET /hello/:person
* GET /hello/person
* GET /hello/people
* GET /hello/person

Examples using any/all of webbrowser, curl, python would be useful.

Thanks

### PR DESCRIPTION
**Pull request by parente**
Fixes #201 when complete

### CODE REVIEW

**Comment by parente** [comment]
@gwvr This PR is incomplete but shows my line of thinking about a better api_intro notebook. I welcome any feedback you have on what's there so far. (You can click the View button in the top right to see the rendered notebook in the files changed tab.)

**Comment by gwvr** [comment]
Thanks @parente, I'll try to keep an eye on this. I can run the notebook through to cell 14 without error, then it barfs on the `filter_by_name` function defined in cell 13. It's certainly more grokkable now.

I did run into issues with the notebook server.
I ran the notebook server with this command:
```bash
jupyter kernelgateway \
--KernelGatewayApp.api='kernel_gateway.notebook_http' \
--KernelGatewayApp.seed_uri='api_intro.ipynb' \
--KernelGatewayApp.prespawn_count=5
```

This throws a bunch of errors (one for each kernel?), like this one:
```
Future <tornado.concurrent.Future object at 0x7efccbaafdd8> exception was never retrieved: Traceback (most recent call last):
  File "/home/anon/.miniconda3/envs/mi/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/anon/.miniconda3/envs/mi/lib/python3.5/site-packages/kernel_gateway/services/kernels/manager.py", line 100, in start_kernel
    raise RuntimeError('Error seeding kernel memory', msg['content'])
RuntimeError: ('Error seeding kernel memory', {'traceback': ['\x1b[0;31m---------------------------------------------------------------------------\x1b[0m', '\x1b[0;31mNameError\x1b[0m                                 Traceback (most recent call last)', "\x1b[0;32m<ipython-input-6-1cb78fed4bfe>\x1b[0m in \x1b[0;36m<module>\x1b[0;34m()\x1b[0m\n\x1b[1;32m      6\x1b[0m     },\n\x1b[1;32m      7\x1b[0m     'path': {\n\x1b[0;32m----> 8\x1b[0;31m         \x1b[0;34m'contact_id'\x1b[0m\x1b[0;34m:\x1b[0m \x1b[0mnew_contact_id\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n\x1b[0m\x1b[1;32m      9\x1b[0m     }\n\x1b[1;32m     10\x1b[0m })\n", "\x1b[0;31mNameError\x1b[0m: name 'new_contact_id' is not defined"], 'evalue': "name 'new_contact_id' is not defined", 'status': 'error', 'payload': [], 'user_expressions': {}, 'execution_count': 6, 'ename': 'NameError', 'engine_info': {'method': 'execute', 'engine_uuid': 'a75fdc00-b2e7-480d-959e-d0d21ee96bad', 'engine_id': -1}})
```

I've updated my conda packages from conda-forge. Tornado is 4.4.2. Let me know if you'd like me to attach my installed conda package list.

**Comment by parente** [comment]
@gwvr Thanks for the feedback. I didn't expect it to be runnable yet so it's good that you confirmed that expectation. 👍 

I'll hopefully get back to it later this week.

**Comment by parente** [comment]
@gwvr I think I've completed the bulk of the tutorial now. If you get a minute, I'd appreciate it if you could give it a try as a review before merge.

**Comment by parente** [comment]
I'm going to go ahead and merge this in order to get a 1.2 out the door. We can continue to iterate anytime.

**Comment by gwvr** [comment]
Thanks @parente, and sorry for the delay. I've just reviewed this and can confirm that I've been able to run it, and it's much more grokkable than previously.

I did have to replace the `python kernel_gateway` command with `jupyter kernelgateway` to run the notebook-http server. Other than that just a typo in the last cell.

**Pull request merged**
